hostname: ros##

rancher:
  network:
    interfaces:
      eth*:
       dhcp: false
      eth0:
       address: 10.0.0.##/24
       gateway: 10.0.0.1
    dns:
      nameservers:
        - 208.67.222.222
        - 208.67.220.220

ssh_authorized_keys:
  - ssh-rsa <public ssh key> rancher@ros##
  
  
