hostname: ros## # https://rancher.com/docs/os/v1.x/en/installation/configuration/hostname/

ssh_authorized_keys: # https://rancher.com/docs/os/v1.x/en/installation/configuration/ssh-keys/
  - ssh-rsa <public ssh key> rancher@ros##

rancher:
  network: # https://rancher.com/docs/os/v1.x/en/installation/networking/
    interfaces: # https://rancher.com/docs/os/v1.x/en/installation/networking/interfaces/
      eth*:
        dhcp: false
      eth0:
        #vlans: 100,200
        address: 10.0.0.##/24
        gateway: 10.0.0.1
    dns: # https://rancher.com/docs/os/v1.x/en/installation/networking/dns/
      nameservers:
        - 208.67.222.222
        - 208.67.220.220
  
#runcmd: # https://rancher.com/docs/os/v1.x/en/installation/configuration/running-commands/
  #  - sudo ros service enable
  
