version: "3"
services:
  dns:
    image: shepner/docker-dnsmasq:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "53:53"
    networks:
      - dnsnet
networks:
  dnsnet:
