debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "my-awesome-app.org"
domain = "mydomainhere.org"
watch = true
exposedbydefault = false

[acme]
#email = "your-email-here@my-awesome-app.org"
email = "name@docker.localhost"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
#storage = "/etc/traefik/acme/acme.json"
#acmeLogging = true
#onDemand = false
