hostname: ros0?

ssh_authorized_keys:
- <public key>

runcmd:
- wget -O /usr/bin/rke https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64
- chmod +x /usr/bin/rke

rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.0.0.?/24
        gateway: 10.0.0.1
    dns:
      nameservers:
      - 208.67.222.222
      - 208.67.220.220
  services_include:
    open-vm-tools: true
