hostname: ros0?

ssh_authorized_keys:
- <public key>

rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.0.0.?/24
        gateway: 10.0.0.1
    dns:
      nameservers:
      - 208.67.222.222
      - 208.67.220.220
  services_include:
    open-vm-tools: true

write_files:
- container: ntp
  path: /etc/ntp.conf
  permissions: "0644"
  owner: root
  content: |
    server 0.pool.ntp.org iburst
    server 1.pool.ntp.org iburst
    server 2.pool.ntp.org iburst
    server 3.pool.ntp.org iburst
    
    # Allow only time queries, at a limited rate, sending KoD when in excess.
    # Allow all local queries (IPv4, IPv6)
    restrict default nomodify nopeer noquery limited kod
    restrict 127.0.0.1
    restrict [::1]
      
runcmd:
# https://rancher.com/docs/rke/latest/en/installation/#download-the-rke-binary
- wget -O /usr/bin/rke https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64 && chmod +x /usr/bin/rke
# https://thomasmodeneis.wordpress.com/2017/06/23/installing-curl-on-rancheros/
- echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl
# https://helm.sh/docs/intro/install/
- wget -P /tmp https://get.helm.sh/helm-`wget https://github.com/helm/helm/releases -O - 2>&1 | grep 'href="/helm/helm/releases/tag/v3.' | grep -v no-underline | head -n 1 | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}' | awk 'a !~ $0{print}; {a=$0}'`-linux-amd64.tar.gz
- gunzip /tmp/helm-* && tar -xf /tmp/helm-*.tar -C /tmp && mv /tmp/linux-amd64/helm /usr/bin/helm
