hostname: ros01

rancher:
  network:
    interfaces:
      eth*:
       dhcp: false
      eth0:
       address: 10.0.0.81/24
       gateway: 10.0.0.1
    dns:
      nameservers:
        - 208.67.222.222
        - 208.67.220.220
