version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    hostname: db
    networks:
      net:
        aliases:
          - db
    volumes:
      - /mnt/nas/docker/zoneminder/mysql:/var/lib/mysql
      - /mnt/nas/docker/zoneminder/conf/mysql:/etc/mysql:ro
    environment:
     - TZ="America/Chicago"
     - MYSQL_USER=zmuser
     - MYSQL_PASSWORD=zmpass
     - MYSQL_DATABASE=zm
     - MYSQL_ROOT_PASSWORD=mysqlpsswd
     - MYSQL_ROOT_HOST=%
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role != manager]
      endpoint_mode: dnsrr
      restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
  zm:
    image: quantumobject/docker-zoneminder
    hostname: zm
    environment:
      - TZ="America/Chicago"
      - ZM_DB_HOST=db
    networks:
      - net
    volumes:
      - /var/empty
      - /mnt/nas/docker/zoneminder/backups:/var/backups
      - /mnt/nas/docker/zoneminder/zoneminder:/var/cache/zoneminder
      - type: tmpfs
        target: /dev/shm
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 0
      #replicas: 1
      placement:
        constraints: [node.role != manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    depends_on:
      - db
networks:
  net:
    driver: overlay
