logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]

  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"

  [entryPoints.https.tls]

[docker]
domain = "example.uk"
watch = true

[acme]
email = "letsencrypt@example.uk"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onDemand = false
OnHostRule = true
